services:
  - type: web
    name: notiq
    env: node
    plan: starter
    buildCommand: npx -y prisma db push --accept-data-loss && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: DATABASE_URL
        sync: false # Must be a hosted DB like Neon or Render Managed Postgres, not localhost!
      - key: GEMINI_API_KEY
        sync: false # Never commit API keys to this file!
